---
language: node_js
sudo: false
env:
  global:
    - COVERAGE=false
    - JSPM_SKIP_PROMPTS=true
    - JSPM_LOG=debug
matrix:
  include:
    - node_js: '10'
    - node_js: '12'
    #
    - node_js: node
      env: COVERAGE=true
before_install:
  - "[ $COVERAGE == false ] || npm install codecov.io"
after_script:
  - "[ $COVERAGE == false ] || npm run istanbul -- --report lcovonly"
  - "[ $COVERAGE == false ] || cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js"
