version = 0.1
default-task = 'build'

extensions = ['chomp@0.1:npm']

[[task]]
name = 'build'
target = 'dist/cli.js'
deps = ['src/*.ts', 'npm:install']
run = 'esbuild src/cli.ts --bundle --platform=node --external:@jspm/generator --external:ora --format=esm --outfile=$TARGET'

[[task]]
name = 'lint'
run = 'eslint .'

[[task]]
name = 'lint:fix'
run = 'eslint . --fix'

[[task]]
name = 'typecheck'
deps = ['src/*.ts', 'test/*.ts']
run = 'tsc --noEmit'

[[task]]
name = 'test'
dep = 'test:'

[[task]]
name = 'test:##'
dep = 'test/##.test.ts'
run = 'tsx $DEP'
