version = 0.1
default-task = 'build'

[[task]]
name = 'build'
dep = 'src/*.ts'
run = 'esbuild src/cli.ts --bundle --platform=node --external:@jspm/generator --format=esm --outfile=dist/cli.js'

[[task]]
name = 'typecheck'
deps = ['src/*.ts', 'test/*.ts']
run = 'tsc --noEmit'

[[task]]
name = 'test'
dep = 'test:'

[[task]]
name = 'test:##'
dep = 'test/##.test.ts'
run = 'tsx $DEP'
